@startuml

skinparam actor {
BorderColor black
BackgroundColor DeepSkyBlue
FontName Aapex
FontSize 17

}
skinparam usecase {
BackgroundColor #A9DCDF
BorderColor DarkSlateGray
ArrowColor DarkSlateGray
ActorBorderColor black
ActorFontName Aapex
ActorFontSize 17
}
left to right direction

actor : 科员（政府端）: as a


usecase 承包方管理 as b
usecase 新增 as b1
usecase 查询 as b2
usecase 修改 as b3
usecase 删除 as b4

usecase 承包方家庭成员管理 as f
usecase 新增 as f1
usecase 查询 as f2
usecase 修改 as f3
usecase 删除 as f4

usecase 承包合同管理 as c
usecase 新增 as c1
usecase 查询 as c2
usecase 修改 as c3
usecase 删除 as c4

usecase 承包经营权证登记簿管理 as d
usecase 查询 as d1
usecase 承包经营权证登记簿变更记录 as d2

usecase 承包经营权证管理 as e
usecase 查询 as e1
usecase 承包经营权证初发 as e2

usecase 权证补发管理 as g
usecase 新增 as g1
usecase 查询 as g2
usecase 权证换发管理 as h
usecase 新增 as h1
usecase 查询 as h2
usecase 权证注销管理 as i
usecase 查询 as i1



a .-> b
a .-> c
a .-> d
a .-> e

b .-> f
b .-> b1
b .-> b2
b .-> b3
b .-> b4

c .-> c1
c .-> c2
c .-> c3
c .-> c4

d .-> d1
d .-> d2

e .-> e1
e .-> e2

e .-> g
e .-> h
e .-> i


f .-> f1
f .-> f2
f .-> f3
f .-> f4

g .-> g1
g .-> g2
h .-> h1
h .-> h2
i .-> i1



@enduml

