@startuml
!include ../style.puml

!if %variable_exists("$THEME")
title Activity Diagram - $THEME theme
!else
title Activity Diagram
!endif

start
:totalCount 待分配的总数量 \r\ntotalAcre   地块总面积 \r\ntotalCount 待分配的总数量 \r\ntotalCount 待分配的总数量 ;

-> test of color;
if (color?) is (<color:red>red) then
  :print red;
else
  :print not red;
  note right: no color
endif
partition End {
  :end;
}
-> this is the end;
end

@enduml

