CREATE TABLE `tbl_loan_apply`
(
    `id`                                   bigint(20) NOT NULL AUTO_INCREMENT,
    `apply_sn`                             varchar(255)                   DEFAULT NULL COMMENT '申请编号，雪花算法生成',
    `company_id`                           bigint(20) DEFAULT NULL COMMENT '企业id，saas系统多租户表示',
    `farm_id`                              bigint(20) NOT NULL COMMENT '农场id',
    `loan_amount`                          decimal(10, 2)                 DEFAULT NULL COMMENT '申请贷款金额（单位：万元，不超过300万）',
    `loan_term`                            int(11) DEFAULT NULL COMMENT '申请期限（单位：年，不超过5年）',
    `fund_use`                             varchar(255)                   DEFAULT NULL COMMENT '资金用途:1:补充生产流动资金；2：固定资产投资',
    `fund_use_remark`                      varchar(255)                   DEFAULT NULL COMMENT '资金用途备注',
    `apply_time`                           datetime                       DEFAULT NULL COMMENT '申请时间',
    `apply_status`                         varchar(255)                   DEFAULT NULL COMMENT '申请状态：10：待联合会审核；20：待银行审核；30：待农业局审核；40：待农担公司审核；50：待签合同；51:待同意放款；52：待放款；53：已放款；54：还款完成；60：审核驳回；70：已取消',
    `reject_trigger_apply_status`          varchar(255)                   DEFAULT NULL COMMENT '触发审核驳回当时的贷款申请状态：00：表示没有触发；10：待联合会审核；20：待银行审核；30：待农业局审核；40：待农担公司审核；',
    `reapply_time`                         datetime                       DEFAULT NULL COMMENT '修改并重新提交时间',
    `reapply_user_id`                      bigint(20) DEFAULT NULL COMMENT '修改并重新提交的人',
    `federation_check_time`                datetime                       DEFAULT NULL COMMENT '联合会审核时间',
    `federation_check_user_id`             bigint(20) DEFAULT NULL COMMENT '联合会审核人',
    `federation_check_result`              varchar(127)                   DEFAULT NULL COMMENT '联合会审核结果：1：通过；2：驳回',
    `federation_view`                      varchar(255)                   DEFAULT NULL COMMENT '联合会审核意见',
    `bank_check_time`                      datetime                       DEFAULT NULL COMMENT '银行审核时间',
    `bank_check_user_id`                   bigint(20) DEFAULT NULL COMMENT '银行审核人',
    `bank_check_result`                    varchar(127)                   DEFAULT NULL COMMENT '银行审核结果：1：通过；2：驳回',
    `bank_view`                            varchar(255)                   DEFAULT NULL COMMENT '银行审核意见',
    `agri_office_check_time`               datetime                       DEFAULT NULL COMMENT '农业局审核时间',
    `agri_office_check_user_id`            bigint(20) DEFAULT NULL COMMENT '农业局审核人',
    `agri_office_check_result`             varchar(127)                   DEFAULT NULL COMMENT '农业局审核结果：1：通过；2：驳回',
    `agri_office_view`                     varchar(255)                   DEFAULT NULL COMMENT '农业局审核意见',
    `agri_insurance_company_check_time`    datetime                       DEFAULT NULL COMMENT '农担公司审核时间',
    `agri_insurance_company_check_user_id` bigint(20) DEFAULT NULL COMMENT '农担公司审核人',
    `agri_insurance_company_check_result`  varchar(127)                   DEFAULT NULL COMMENT '农担公司审核结果：1：通过；2：驳回',
    `agri_insurance_company_view`          varchar(255)                   DEFAULT NULL COMMENT '农担公司审核意见',
    `upload_loan_contract_time`            datetime                       DEFAULT NULL COMMENT '银行上传借款合同时间',
    `upload_loan_contract_user_id`         bigint(20) DEFAULT NULL COMMENT '银行上传借款合同操作人',
    `upload_loan_contract_explain`         varchar(255)                   DEFAULT NULL COMMENT '银行上传借款合同说明',
    `agree_loan_time`                      datetime                       DEFAULT NULL COMMENT '农担公司同意放款时间',
    `agree_loan_user_id`                   bigint(20) DEFAULT NULL COMMENT '同意放款操作人',
    `agree_loan_explain`                   varchar(255)                   DEFAULT NULL COMMENT '农担公司同意放款说明',
    `sign_make_loan_time`                  datetime                       DEFAULT NULL COMMENT '银行标记已放款时间',
    `sign_make_loan_user_id`               bigint(20) DEFAULT NULL COMMENT '银行标记已放款操作人',
    `sign_make_loan_explain`               varchar(255)                   DEFAULT NULL COMMENT '银行标记已放款说明',
    `repayment_flag`                       tinyint(4) DEFAULT NULL COMMENT '还款标签：1：正常；2：异常；(该值只有已放款状态才有值)3：尚未开始',
    `repayment_flag_view`                  varchar(255)                   DEFAULT NULL COMMENT '还款标记说明',
    `mark_repayment_completed_time`        datetime                       DEFAULT NULL COMMENT '农担公司标记完成还款时间',
    `mark_repayment_completed_user_id`     bigint(20) DEFAULT NULL COMMENT '农担公司标记完成还款操作人',
    `mark_repayment_completed_explain`     varchar(255)                   DEFAULT NULL COMMENT '农担公司标记完成还款说明',
    `canceled_time`                        datetime                       DEFAULT NULL COMMENT '取消申请时间',
    `canceled_user_id`                     bigint(20) DEFAULT NULL COMMENT '取消申请的人',
    `file_id0`                             varchar(255)                   DEFAULT NULL COMMENT '家庭农场信贷直通车项目库',
    `file_id1`                             varchar(255)                   DEFAULT NULL COMMENT '项目推荐确认审核表id',
    `file_id11`                            varchar(255)                   DEFAULT NULL COMMENT '调查报告',
    `file_id12`                            varchar(255)                   DEFAULT NULL COMMENT '担保申请表',
    `file_id2`                             varchar(255)                   DEFAULT NULL COMMENT '“家庭农场信贷直通车”信贷项目确认函id',
    `file_id3`                             varchar(255)                   DEFAULT NULL COMMENT '同意担保决议函附件id',
    `file_id4`                             varchar(255)                   DEFAULT NULL COMMENT '借款合同',
    `file_id5`                             varchar(255)                   DEFAULT NULL COMMENT '同意放(用)款通知书id',
    `file_id6`                             varchar(255)                   DEFAULT NULL COMMENT '解保通知书id',
    `company_loan_basic_info_id`           bigint(20) DEFAULT NULL COMMENT '企业基本信息id',
    `company_name`                         varchar(255)                   DEFAULT NULL COMMENT '企业名称',
    `farm_loan_basic_info_id`              bigint(20) DEFAULT NULL COMMENT '贷款农场基本信息表id',
    `farm_name`                            varchar(255)                   DEFAULT NULL COMMENT '农场名称',
    `farm_province_id`                     varchar(64)                    DEFAULT NULL COMMENT '所在省份id',
    `farm_province_name`                   varchar(64)                    DEFAULT NULL COMMENT '所在省份名称',
    `farm_city_id`                         varchar(64)                    DEFAULT NULL COMMENT '所在城市id',
    `farm_city_name`                       varchar(64)                    DEFAULT NULL COMMENT '所在城市名称',
    `farm_county_id`                       varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '区/县id',
    `farm_county_name`                     varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '区/县名称',
    `farm_town_id`                         varchar(64)                    DEFAULT NULL COMMENT '镇id',
    `farm_town_name`                       varchar(64)                    DEFAULT NULL COMMENT '镇名称',
    `farm_village_id`                      varchar(64)                    DEFAULT NULL COMMENT '村id',
    `farm_village_name`                    varchar(64)                    DEFAULT NULL COMMENT '村名称',
    `farm_address`                         varchar(256)                   DEFAULT NULL COMMENT '详细地址',
    `loan_member_info_id`                  bigint(20) DEFAULT NULL COMMENT '贷款申请人员信息表id',
    `applier_full_name`                    varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员姓名',
    `loan_area_bank_id`                    bigint(20) DEFAULT NULL COMMENT '区域放贷机构主键id',
    `loan_area_bank_name`                  varchar(255)                   DEFAULT NULL COMMENT '机构名称',
    `create_by`                            bigint(20) DEFAULT NULL,
    `create_time`                          datetime                       DEFAULT NULL,
    `update_by`                            bigint(20) DEFAULT NULL,
    `update_time`                          datetime                       DEFAULT NULL,
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=155 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='贷款申请表';


CREATE TABLE `tbl_loan_apply_extend`
(
    `apply_sn`                                   varchar(255)                   DEFAULT NULL COMMENT '申请编号，雪花算法生成',
    `qualification_business_img_url`             text COMMENT '营业执照url',
    `enterprise_credit_code`                     varchar(64)                    DEFAULT NULL COMMENT '企业（统一社会）信用代码',
    `farm_loan_business_rank`                    varchar(255)                   DEFAULT NULL COMMENT '示范等级：1：国家级；2：省级；3：市级；4：区县级；5：否',
    `farm_loan_business_operating_area`          decimal(10, 2)                 DEFAULT NULL COMMENT '经营面积',
    `farm_loan_business_main_business`           varchar(255)                   DEFAULT NULL COMMENT '主营业务：1：粮油种植；2：特色农产品种植；3：生猪养殖；4：其他畜牧业；5：渔业生产；6：农田建设；7：农资、农机、农技等农业社会化服务；\r\n8：农产品流通（含农产品收购、仓储保鲜、销售等）；9：农产品初加工；10：非农业生产；11：种子生产、加工及销售；12：农业科创；13：休闲文旅；',
    `farm_loan_business_img_urls`                text COMMENT '门头标牌及经营现状照片,多个照片逗号隔开',
    `farm_loan_business_farm_account_img_urls`   text COMMENT '家庭农场台账照片,多个照片逗号隔开',
    `loan_land_transfer_contract_id`             bigint(20) DEFAULT NULL COMMENT '贷款农场申请土地流转合同信息表id',
    `loan_land_transfer_contract_start_time_str` varchar(255)                   DEFAULT NULL COMMENT '贷款农场申请土地流转合同起始日期',
    `loan_land_transfer_contract_end_time_str`   varchar(255)                   DEFAULT NULL COMMENT '贷款农场申请土地流转合同结束日期',
    `loan_land_transfer_contract_img_urls`       text COMMENT '贷款农场申请土地流转合同合同照片,多个照片逗号隔开',
    `applier_identify_number`                    varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员证件号',
    `applier_phone_number`                       varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员手机号',
    `applier_province_id`                        varchar(64)                    DEFAULT NULL COMMENT '贷款申请人员所在省份id',
    `applier_province_name`                      varchar(64)                    DEFAULT NULL COMMENT '贷款申请人员所在省份名称',
    `applier_city_id`                            varchar(64)                    DEFAULT NULL COMMENT '贷款申请人员所在城市id',
    `applier_city_name`                          varchar(64)                    DEFAULT NULL COMMENT '贷款申请人员所在城市名称',
    `applier_county_id`                          varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '贷款申请人员区/县id',
    `applier_county_name`                        varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '贷款申请人员区/县名称',
    `applier_address`                            varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员详细住址',
    `applier_wedding_status`                     tinyint(4) DEFAULT NULL COMMENT '贷款申请人员婚姻状况 1：未婚；2：已婚；3：离异；4：丧偶',
    `applier_front_of_id_card_img_url`           varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员身份证正面照片',
    `applier_back_of_id_card_img_url`            varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员身份证反面照片',
    `applier_household_register_img_urls`        text COMMENT '贷款人员户口本照片',
    `applier_marriage_img_urls`                  varchar(255)                   DEFAULT NULL COMMENT '贷款人员结婚证照片',
    `applier_spouse_full_name`                   varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员配偶姓名',
    `applier_spouse_identify_number`             varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员配偶证件号',
    `applier_spouse_phone_number`                varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员配偶手机号',
    `applier_family_member_full_name`            varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员其他家庭成员姓名',
    `applier_family_member_identify_number`      varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员其他家庭成员证件号',
    `applier_family_member_phone_number`         varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员其他家庭成员手机号',
    `applier_family_member_province_id`          varchar(64)                    DEFAULT NULL COMMENT '贷款申请人员其他家庭成员所在省份id',
    `applier_family_member_province_name`        varchar(64)                    DEFAULT NULL COMMENT '贷款申请人员其他家庭成员所在省份名称',
    `applier_family_member_city_id`              varchar(64)                    DEFAULT NULL COMMENT '贷款申请人员其他家庭成员所在城市id',
    `applier_family_member_city_name`            varchar(64)                    DEFAULT NULL COMMENT '贷款申请人员其他家庭成员所在城市名称',
    `applier_family_member_county_id`            varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '贷款申请人员其他家庭成员区/县id',
    `applier_family_member_county_name`          varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '贷款申请人员其他家庭成员区/县名称',
    `applier_family_member_address`              varchar(255)                   DEFAULT NULL COMMENT '贷款申请人员其他家庭成员详细住址',
    `relationship`                               varchar(255)                   DEFAULT NULL COMMENT '与申请人关系：1：父亲；2：母亲；3：儿子；4：女儿；',
    `bank_province_id`                           varchar(64)                    DEFAULT NULL COMMENT '所在省份id',
    `bank_province_name`                         varchar(64)                    DEFAULT NULL COMMENT '所在省份名称',
    `bank_city_id`                               varchar(64)                    DEFAULT NULL COMMENT '所在城市id',
    `bank_city_name`                             varchar(64)                    DEFAULT NULL COMMENT '所在城市名称',
    `bank_county_id`                             varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '区/县id',
    `bank_county_name`                           varchar(64) CHARACTER SET utf8 DEFAULT NULL COMMENT '区/县名称',
    `bank_short_name`                            varchar(255)                   DEFAULT NULL COMMENT '机构简称',
    `bank_logo_img_url`                          varchar(255)                   DEFAULT NULL COMMENT '机构logo图片',
    `bank_loan_rate`                             varchar(255)                   DEFAULT NULL COMMENT '放贷利率描述',
    `bank_repayment_method_info`                 varchar(255)                   DEFAULT NULL COMMENT '还款方式描述',
    `bank_min_loan_amount`                       decimal(10, 2)                 DEFAULT NULL COMMENT '贷款金额下限(万元）',
    `bank_max_loan_amount`                       decimal(10, 2)                 DEFAULT NULL COMMENT '贷款金额上限(万元）',
    `bank_max_loan_term`                         tinyint(4) DEFAULT NULL COMMENT '贷款期限上线',
    `bank_policy_img_url`                        varchar(255)                   DEFAULT NULL COMMENT '机构政策图片',
    UNIQUE KEY `unq_apply_sn` (`apply_sn`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='贷款申请扩展表';


-- --------------------------------------归档表------------------------------------------------

CREATE TABLE `tbl_archive_loan_apply_area_month`
(
    `id`                        bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `area_id`                   varchar(64) NOT NULL COMMENT '区域id，可以是省、市、区、镇、村等编码id',
    `area_name`                 varchar(64)    DEFAULT NULL COMMENT '区域名称，可以是省、市、区、镇、村等的名称',
    `archive_month`             varchar(64) NOT NULL COMMENT '归档月份（yyyy-mm）',

    `loan_count`                int(11) DEFAULT NULL COMMENT '申请贷款农场数（家）',
    `loan_amount`               decimal(16, 2) DEFAULT NULL COMMENT '申请贷款总金额（万元）',
    `issued_loan_count`         int(11) DEFAULT NULL COMMENT '获得贷款农场数（家）',
    `issued_loan_amount`        decimal(16, 2) DEFAULT NULL COMMENT '发放贷款总金额（万元）',

    `loan_count_level1`         int(11) DEFAULT NULL COMMENT '申请金额在0-50万之间申请贷款农场数（家）',
    `loan_amount_level1`        decimal(16, 2) DEFAULT NULL COMMENT '申请金额在0-50万之间申请贷款总金额（万元）',
    `issued_loan_count_level1`  int(11) DEFAULT NULL COMMENT '申请金额在0-50万之间获得贷款农场数（家）',
    `issued_loan_amount_level1` decimal(16, 2) DEFAULT NULL COMMENT '申请金额在0-50万之间发放贷款总金额（万元）',

    `loan_count_level2`         int(11) DEFAULT NULL COMMENT '申请金额在51-100万之间申请贷款农场数（家）',
    `loan_amount_level2`        decimal(16, 2) DEFAULT NULL COMMENT '申请金额在51-100万之间申请贷款总金额（万元）',
    `issued_loan_count_level2`  int(11) DEFAULT NULL COMMENT '申请金额在51-100万之间获得贷款农场数（家）',
    `issued_loan_amount_level2` decimal(16, 2) DEFAULT NULL COMMENT '申请金额在51-100万之间发放贷款总金额（万元）',

    `loan_count_level3`         int(11) DEFAULT NULL COMMENT '申请金额在101-150万之间申请贷款农场数（家）',
    `loan_amount_level3`        decimal(16, 2) DEFAULT NULL COMMENT '申请金额在101-150万之间申请贷款总金额（万元）',
    `issued_loan_count_level3`  int(11) DEFAULT NULL COMMENT '申请金额在101-150万之间获得贷款农场数（家）',
    `issued_loan_amount_level3` decimal(16, 2) DEFAULT NULL COMMENT '申请金额在101-150万之间发放贷款总金额（万元）',

    `loan_count_level4`         int(11) DEFAULT NULL COMMENT '申请金额在151-200万之间申请贷款农场数（家）',
    `loan_amount_level4`        decimal(16, 2) DEFAULT NULL COMMENT '申请金额在151-200万之间申请贷款总金额（万元）',
    `issued_loan_count_level4`  int(11) DEFAULT NULL COMMENT '申请金额在151-200万之间获得贷款农场数（家）',
    `issued_loan_amount_level4` decimal(16, 2) DEFAULT NULL COMMENT '申请金额在151-200万之间发放贷款总金额（万元）',

    `loan_count_level5`         int(11) DEFAULT NULL COMMENT '申请金额在201-300万之间申请贷款农场数（家）',
    `loan_amount_level5`        decimal(16, 2) DEFAULT NULL COMMENT '申请金额在201-300万之间申请贷款总金额（万元）',
    `issued_loan_count_level5`  int(11) DEFAULT NULL COMMENT '申请金额在201-300万之间获得贷款农场数（家）',
    `issued_loan_amount_level5` decimal(16, 2) DEFAULT NULL COMMENT '申请金额在201-300万之间发放贷款总金额（万元）',

    `loan_count_level6`         int(11) DEFAULT NULL COMMENT '申请金额在300万及以上申请贷款农场数（家）',
    `loan_amount_level6`        decimal(16, 2) DEFAULT NULL COMMENT '申请金额在300万及以上申请贷款总金额（万元）',
    `issued_loan_count_level6`  int(11) DEFAULT NULL COMMENT '申请金额在300万及以上获得贷款农场数（家）',
    `issued_loan_amount_level6` decimal(16, 2) DEFAULT NULL COMMENT '申请金额在300万及以上发放贷款总金额（万元）',


    `statistics_mode`           tinyint(2) DEFAULT NULL COMMENT '统计方式 0 手动 1 自动',
    `create_time`               datetime       DEFAULT NULL COMMENT '创建时间',
    `update_time`               datetime       DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='担保贷贷款农场数、贷款金额按区域按月归档表';

CREATE TABLE `tbl_archive_loan_apply_area_bank`
(
    `area_id`                   varchar(64) NOT NULL COMMENT '区域id，可以是省、市、区、镇、村等编码id',
    `area_name`                 varchar(64)    DEFAULT NULL COMMENT '区域名称，可以是省、市、区、镇、村等的名称',
    `loan_area_bank_id`         varchar(64) NOT NULL COMMENT '放贷机构id',
    `loan_area_bank_short_name` varchar(255)   DEFAULT NULL COMMENT '放贷机构简称',

    `loan_count`                int(11) DEFAULT NULL COMMENT '申请贷款农场数（家）',
    `loan_amount`               decimal(16, 2) DEFAULT NULL COMMENT '申请贷款总金额（万元）',
    `issued_loan_count`         int(11) DEFAULT NULL COMMENT '获得贷款农场数（家）',
    `issued_loan_amount`        decimal(16, 2) DEFAULT NULL COMMENT '发放贷款总金额（万元）',

    `statistics_mode`           tinyint(2) DEFAULT NULL COMMENT '统计方式 0 手动 1 自动',
    `create_time`               datetime       DEFAULT NULL COMMENT '创建时间',
    `update_time`               datetime       DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='担保贷贷款农场数、贷款金额按区域按放贷机构归档表';

CREATE TABLE `tbl_archive_loan_apply_area_main_business`
(
    `id`                 bigint(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
    `area_id`            varchar(64)    DEFAULT NULL COMMENT '区域id，可以是省、市、区、镇、村等编码id',
    `main_business_type` varchar(64) NOT NULL COMMENT '主营业务类型',
    `main_business_name` varchar(64) NOT NULL COMMENT '主营业务名称',

    `loan_count`         int(11) DEFAULT NULL COMMENT '申请贷款农场数（家）',
    `loan_amount`        decimal(16, 2) DEFAULT NULL COMMENT '申请贷款总金额（万元）',
    `issued_loan_count`  int(11) DEFAULT NULL COMMENT '获得贷款农场数（家）',
    `issued_loan_amount` decimal(16, 2) DEFAULT NULL COMMENT '发放贷款总金额（万元）',

    `statistics_mode`    tinyint(2) DEFAULT NULL COMMENT '统计方式 0 手动 1 自动',
    `create_time`        datetime       DEFAULT NULL COMMENT '创建时间',
    `update_time`        datetime       DEFAULT NULL COMMENT '更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8mb4 COMMENT='担保贷贷款农场数、贷款金额按区域按主营业务归档表';