
@startuml

hide empty description
[*] -> 1.草稿 #86c8b5:保存草稿-新增
[*] --> 2.待审核 #deeppink:提交审核-新增
1.草稿 -> 2.待审核 :提交审核
1.草稿 -> 1.草稿 :保存草稿-编辑


2.待审核--> 1.草稿 :撤回
2.待审核 --> 3.已通过 #deeppink:审核通过
2.待审核 --> 4.被驳回 #deeppink:审核驳回或定时器自动驳回
4.被驳回 --> 1.草稿 :重新提交
3.已通过 --> [*]
1.草稿 -> [*]  :删除
@enduml