@startuml
!include ../style.puml
autonumber  "0."

 actor 总监或中队长 as 任务管理者
participant "produce服务" as A

autonumber  "0."
任务管理者->A:修改
activate A


A -> A: 入参校验
A -> A: <1>校验农事任务状态是否为**“待接受”**\n<2>校验用户信息是否合法\n<3>校验任务类型及农事类型\n<4>校验农事任务地块入参集合\n<5>当作业方式等于机械时,校验农事任务农机入参的农机种类id、农机出库数量\n<6>当农事类型是否使用农资大类字段有值时，校验农事任务农资入参农资id、农资出库数量\n<7>当农事任务类型是否创建种植计划等于是时，校验作物id是否有效\n<8>当农事任务类型是否生成采收计划等于是时，校验种养计划id是否有效

A -> A: 组装农事任务数据,并更新'农事任务表'
A -> A: 组装农事任务地块数据，先删除该农事任务下的农事任务地块，后插入'农事任务地块表'

A -> A: 当农事类型是否使用农资大类字段有有效值时，组装农事任务农资数据，先删除该农事任务下的农事任务农资，并插入'农事任务农资表'

A -> A: 当作业方式等于机械时，组装农事任务农机数据，先删除该农事任务下的农事任务农机，并插入'农事任务农机表'

A -> A: 组装农事任务变更记录数据,并插入'农事任务变更记录表'
A --> 任务管理者: 返回结果
deactivate A




@enduml