@startuml
!include ../style.puml
autonumber  "0."

 actor 小队长 as 任务执行者
participant "produce服务" as A


autonumber  "0."

任务执行者->A:接受
activate A
A -> A: 入参校验
A -> A: <1>校验农事任务状态是否为**“待接受”**\n<2>校验用户信息是否合法

group 判断该农事任务是否需要农资和农机

else 情况一: 既不需要农资，又不需要农机

A -> A: 将农事任务数据状态改为**“待执行”**,并更新'农事任务表'
A -> A: 组装农事任务变更记录数据,并插入'农事任务变更记录表'
A --> 任务执行者: 返回结果

else 情况二: 需要农资，不需要农机
A -> A: 将农事任务数据状态改为**“仓储处理中”**,并更新'农事任务表'
A -> A: 创建农资出库子任务状态赋值为**“待出库”**,并插入'农资出库任务表'
A -> A: 组装农事任务变更记录数据,并插入'农事任务变更记录表'
A --> 任务执行者: 返回结果

else 情况三: 不需要农资，需要农机
A -> A: 将农事任务数据状态改为**“仓储处理中”**,并更新'农事任务表'
A -> A: 创建农机领用子任务状态赋值为**“待处理”**,并插入'农机领用任务表'
A -> A: 组装农事任务变更记录数据,并插入'农事任务变更记录表'
A --> 任务执行者: 返回结果


else 情况四: 既需要农资，又需要农机
A -> A: 将农事任务数据状态改为**“仓储处理中”**,并更新'农事任务表'
A -> A: 创建农资出库子任务状态赋值为**“待出库”**,并插入'农资出库任务表'
A -> A: 创建农机领用子任务状态赋值为**“待处理”**,并插入'农机领用任务表'
A -> A: 组装农事任务变更记录数据,并插入'农事任务变更记录表'
A --> 任务执行者: 返回结果

end

@enduml