@startuml
!include ../style.puml
autonumber  "0."

 actor 总监或中队长 as 任务管理者
participant "produce服务" as A


autonumber  "0."
任务管理者->A:确认完成
activate A
A -> A: 入参校验
A -> A: <1>校验农事任务状态是否为**“执行完毕”**\n<2>校验用户信息是否合法
A -> A: <1>填入任务评分、任务评价等信息\n<2>将农事任务数据状态改为**“完成”**,并更新'农事任务表'

A -> A: 创建农事记录
A -> A: 当农事任务类型是否创建种植计划等于是时，校验作物id是否有效,并创建种养计划
A -> A: 当农事任务类型是否生成采收计划等于是时，校验种养计划id是否有效，并创建采收记录

A -> A: 组装农事任务变更记录数据,并插入'农事任务变更记录表'
A --> 任务管理者: 返回结果
deactivate A

@enduml