@startuml
!include ../style.puml
autonumber  "0."

 actor 小队长 as 任务执行者
participant "produce服务" as A


autonumber  "0."

任务执行者->A:提交任务


activate A
A -> A: 入参校验
A -> A: <1>校验农事任务状态是否为**“待执行”**\n<2>校验用户信息是否合法\n<3>校验农事任务劳作人员工时集合信息

A -> A: <1>将农事任务数据状态改为**“执行完毕”**\n<2>填入工作图片url、执行人、实际任务时间等等信息\n<3>更新'农事任务表'


A -> A: 组装农事任务劳作人员工时集合数据，并插入'农事任务劳作人员工时表'

A -> A: 组装农事任务变更记录数据,并插入'农事任务变更记录表'
A --> 任务执行者: 返回结果

deactivate A



@enduml