@startuml
!include ../style.puml
autonumber  "0."

actor 农机库管员
participant "produce服务" as A


农机库管员->A:删除农机出入记录
activate A
A -> A: 入参校验
A -> A: \n<1> 校验目标删除的农机出入库记录是否存在\n<2>校验农机领用子任务状态是否为**“待处理”**\n<3>校验用户信息是否合法

A -> A: <1>查询农事任务农机信息\n<2>查询该农机领用子任务的农机出入库记录列表

A -> A:判断农事任务农机已领用数量是否大于本次农事任务农机该领用的量，\n若是则操作'农机出入记录表'删除该条记录
A -> A: 计算农事任务农机已出库数量字段,并更新'农事任务农机表'


A --> 农机库管员: 返回结果
deactivate A

@enduml