@startuml
!include ../style.puml
  skinparam arrow {
    Color deeppink
	Thickness 1
	fontsize 10
	fontcolor #blue
  }

left to right direction

actor :企业端用户 :as a
usecase 管理农场
  a --> (管理农场)
  管理农场 --> (新增)
  管理农场 --> (修改)
  管理农场 --> (删除)


 (删除)--> (删除地块)
 (删除)--> (删除农场检测报告)
  (删除)--> (删除种植计划：农林牧渔)
  (删除)--> (删除采收计划：农林牧渔)
 (删除)--> (删除农事)
 (删除)--> (删除农事投入品)
 (删除)--> (删除农事参与人)
 (删除)--> (删除农场秀)

@enduml