@startuml
!include ../uml/style.puml


'skinparam linetype ortho
  skinparam arrow {
    Color deeppink
	Thickness 1
	fontsize 10
	fontcolor #blue
  }
entity "农机大类表" as 农机大类表 {
  主键
  --
农机大类唯一标识
}

entity "农机小类表" as 农机小类表 {
  主键
  --
农机大类主键
}

entity "农机种类表" as 农机种类表 {
  主键
  --
农机小类主键
}

entity "农机表" as 农机表 {
  主键
  --
农机种类主键
}

entity "农机出入记录表" as 农机出入记录表 {
  主键
  --
 农机领用任务主键
  --
 农机主键
}

entity "农资出入库记录表" as 农资出入库记录表 #f0ad4e {
  主键
  --
  农资出库任务主键
  --
 农资主键
}

entity "农事类型表" as 农事类型表 #f0ad4e {
  主键
  --
  农事类型唯一标志
}


entity "种养计划表" as 种养计划表 #f0ad4e {
  主键

}


entity "采收记录表" as 采收记录表 #f0ad4e {
  主键

}


entity "农事记录表" as 农事记录表 #f0ad4e {
  主键

}



entity "农事任务表" as 农事任务表 {
      主键                         \n\n
  --
  任务编号                        \n\n
  --
  任务类型主键                       \n\n
}

entity "农资出库任务" as 农资出库任务 {
  任务编号
}

entity "农机领用任务" as 农机领用任务 {

  任务编号

}


entity "农事任务变更记录表" as 农事任务变更记录表 {
  主键
  --
 农事任务主键
}

entity "农事任务农资表" as 农事任务农资表 {
  农事任务主键
  --
  农资主键
}

entity "农事任务农机表" as 农事任务农机表 {
  农事任务主键
  --
  农机主键
}

entity "农事任务地块表" as 农事任务地块表 {
  农事任务主键
  --
  地块主键
}

entity "任务类型表" as 任务类型表 {
  主键
  --
  农事类型唯一标识
}

entity "农事任务劳作人员表" as 农事任务劳作人员表 {
主键
}

entity "农事任务劳作人员工时表" as 农事任务劳作人员工时表 {
 农事任务主键
 --
 农事任务劳作人员主键
}


任务类型表 ||--o{ 农事任务表
农事类型表 ||--|| 任务类型表


农事任务表 ||----|| 农资出库任务
农事任务表 ||----|| 农机领用任务



农事任务表 ||-o{ 种养计划表
农事任务表 ||-o{ 采收记录表
农事任务表 ||-|| 农事记录表



农事任务表 ||--o{ 农事任务农资表
农事任务表 ||--o{ 农事任务农机表
农事任务表 ||--o{ 农事任务地块表
农事任务表 ||---o{ 农事任务变更记录表

农事任务表 ||--o{ 农事任务劳作人员工时表
农事任务劳作人员表 ||-o{ 农事任务劳作人员工时表

农机领用任务 ||--o{  农机出入记录表
农资出库任务 ||--o{  农资出入库记录表




农机出入记录表}o--|| 农机表
农机大类表 ||-o{ 农机小类表
农机小类表 ||-o{ 农机种类表
农机种类表 ||-o{ 农机表



@enduml


