@startuml

skinparam defaultFontName       "XHei"
skinparam defaultFontSize       12
skinparam dpi                   100
skinparam shadowing             false
skinparam roundcorner           8
skinparam ParticipantPadding    40
skinparam BoxPadding            40
skinparam Padding               5
skinparam ArrowColor            #343a40
skinparam stereotype {
    CBackgroundColor #f4a1a4
    CBorderColor #db878b
    ABackgroundColor #67d1a7
    ABorderColor #4db88d
    IBackgroundColor #ff8662
    IBorderColor #e66c49
    EBackgroundColor #ffd376
    EBorderColor #e6b95d
    NBackgroundColor #7bc9d9
    NBorderColor #61b0c0
}
skinparam title {
	FontColor	                 #000000
	BorderColor	                 #db878b
	FontSize	    	         20
	BorderRoundCorner            8
	BorderThickness 	         1
	BackgroundColor              #f4a1a4-#f3969a
}

skinparam legend {
	BackgroundColor #f3969a
	BorderColor #db878b
	FontColor #000000
}

skinparam swimlane {
	BorderColor #6cc3d5
	BorderThickness 2
	TitleBackgroundColor  #f4a1a4-#f3969a
	TitleFontColor #000000
}


skinparam activity {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
	BarColor #56cc9d
	StartColor #6cc3d5
	EndColor #6cc3d5
	DiamondBackgroundColor #f4a1a4
  	DiamondBorderColor #db878b
  	DiamondFontColor #000000
}


skinparam participant {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
	ParticipantBorderThickness 2
}


skinparam actor {
	FontColor #000000
	BorderColor #343a40
	BackgroundColor #86c8b5
}


skinparam arrow {
	Thickness 2
	Color #78c2ad
	FontColor #000000
}


skinparam sequence {
	BorderColor #78c2ad
	TitleFontColor #000000
	BackgroundColor transparent
	StartColor #78c2ad
	EndColor #78c2ad
	BoxBackgroundColor transparent
	BoxBorderColor #343a40
	BoxFontColor #000000
	DelayFontColor #000000
	LifeLineBorderColor #f3969a
	LifeLineBorderThickness 3
	LifeLineBackgroundColor #db878b
	GroupBorderColor #343a40
	GroupFontColor #000000
	GroupHeaderFontColor #000000
	GroupBackgroundColor #f3969a
	GroupBodyBackgroundColor transparent
	GroupHeaderBackgroundColor transparent
	DividerBackgroundColor #343a40
    DividerBorderColor #343a40
    DividerBorderThickness 2
    DividerFontColor #f8f9fa
	ReferenceBackgroundColor transparent
	ReferenceBorderColor #343a40
	ReferenceFontColor #343a40
	ReferenceHeaderFontColor #6cc3d5
	ReferenceHeaderBackgroundColor #f3969a
	StereotypeFontColor #000000
}


skinparam partition {
	BorderColor #78c2ad
	FontColor #78c2ad
	BackgroundColor transparent
}


skinparam collections {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
}


skinparam control {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
}


skinparam entity {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
}


skinparam boundary {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
}


skinparam agent {
	BackgroundColor #ffce67
	BorderColor #ffd376
	FontColor #343a40
}


skinparam note {
	BorderThickness 1
	BackgroundColor #6cc3d5
	BorderColor #61b0c0
	FontColor #000000
}


skinparam artifact {
	BackgroundColor #343a40
	BorderColor #2f343a
	FontColor #f8f9fa
}


skinparam component {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
}


skinparam interface {
	BackgroundColor  #e66c49
	BorderColor  #ff7851
	FontColor #343a40
}


skinparam storage {
	BackgroundColor #ffce67
  	BorderColor #e6b95d
	FontColor #000000
}


skinparam node {
	BackgroundColor  #f3969a
	BorderColor #f8f9fa
	FontColor #f8f9fa
}


skinparam cloud {
	BackgroundColor transparent
	BorderColor #F2FCFE
	FontColor #343a40
}


skinparam database {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
}


skinparam class {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
	HeaderBackgroundColor #86c8b5
	StereotypeFontColor #343a40
	BorderThickness 1
	AttributeFontColor #343a40
	AttributeFontSize 11
}


skinparam object {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
	StereotypeFontColor #343a40
	BorderThickness 1
	AttributeFontColor #000000
	AttributeFontSize 11
}


skinparam usecase {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
	BorderThickness 2
	StereotypeFontColor #78c2ad
}


skinparam rectangle {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
	BackgroundColor #F0FFF0
	BorderThickness 2
	StereotypeFontColor #78c2ad
}


skinparam package {
	BackgroundColor #f3969a
  	BorderColor #78c2ad
	FontColor #78c2ad
	BorderThickness 2
}


skinparam folder {
	BackgroundColor #f4a1a4
  	BorderColor #ffce67
	FontColor #ffce67
	BorderThickness 2
}


skinparam frame {
	BackgroundColor #f4a1a4
  	BorderColor #6cc3d5
	FontColor #6cc3d5
	BorderThickness 2
}


skinparam state {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
	StartColor #darkcyan
	EndColor #darkcyan
	AttributeFontColor #000000
	AttributeFontSize 11
}


skinparam queue {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
}


skinparam card {
	BackgroundColor #6cc3d5
	BorderColor #61b0c0
	FontColor #000000
}
skinparam file {
	BackgroundColor #db878b
	BorderColor #f8f9fa
	FontColor #f8f9fa
}
skinparam stack {
		FontColor #000000
	BorderColor #78c2ad
	BackgroundColor #86c8b5
}











@enduml