@startuml
!include ../style.puml
  skinparam arrow {
    Color deeppink
	Thickness 1
	fontsize 10
	fontcolor #blue
  }

left to right direction
actor 总监
actor 中队长
actor 小队长
actor 任务管理者
actor 任务执行者


中队长--|>任务管理者
总监--|>任务管理者
任务执行者<|--小队长


  任务管理者 --> (提出农事任务)
  任务管理者 --> (确认农事任务完成情况)

  (收到农事任务消息) <-- 任务执行者
  (执行农事任务) <-- 任务执行者
  (提交农事任务执行结果) <-- 任务执行者

@enduml