
@startuml
hide empty description
[*] -> 1_草稿 :保存草稿-新增
[*] -> 2_待审核 :提交审核-新增
1_草稿 -> 2_待审核 :提交审核
1_草稿 -> 1_草稿 :保存草稿-编辑


2_待审核--> 1_草稿 :撤回
2_待审核 --> 3_已通过 :审核通过
2_待审核 --> 4_被驳回 :审核驳回或定时器自动驳回
4_被驳回 -> 1_草稿 :重新提交
3_已通过 --> [*]
1_草稿 -> [*]  :删除
@enduml