@startuml
!include ../style.puml
  skinparam arrow {
    Color deeppink
	Thickness 1
	fontsize 10
	fontcolor #blue
  }

left to right direction
actor 总监
actor 中队长
actor :任务提出者(co端) :as 任务提出者

中队长--|>任务提出者
总监--|>任务提出者

rectangle 提出农事任务 {



usecase 创建农事任务变更记录 as 创建农事任务变更记录1
usecase 创建农事任务变更记录 as 创建农事任务变更记录2
usecase 创建农事任务变更记录 as 创建农事任务变更记录3



usecase 管理农事任务农资 as 管理农事任务农资1
usecase 管理农事任务农资 as 管理农事任务农资2
usecase 新增 as 农事任务农资新增1
usecase 新增 as 农事任务农资新增2
usecase 修改 as 农事任务农资修改2
usecase 删除 as 农事任务农资删除2

usecase 管理农事任务农机 as 管理农事任务农机1
usecase 管理农事任务农机 as 管理农事任务农机2
usecase 新增 as 农事任务农机新增1
usecase 新增 as 农事任务农机新增2
usecase 修改 as 农事任务农机修改2
usecase 删除 as 农事任务农机删除2

usecase 管理农事任务地块 as 管理农事任务地块1
usecase 管理农事任务地块 as 管理农事任务地块2
usecase 新增 as 农事任务地块新增1
usecase 新增 as 农事任务地块新增2
usecase 修改 as 农事任务地块修改2
usecase 删除 as 农事任务地块删除2


任务提出者 --> (创建农事任务)
  (创建农事任务) ..> (创建农事任务变更记录1) : include
  (创建农事任务) <.. (管理农事任务农资1) : extends
  (创建农事任务) <.. (管理农事任务农机1) : extends
  (创建农事任务) ..> (管理农事任务地块1) : include
    (管理农事任务农资1)-->(农事任务农资新增1)
    (管理农事任务农机1)-->(农事任务农机新增1)
    (管理农事任务地块1)-->(农事任务地块新增1)


任务提出者 --> (编辑农事任务)
 (编辑农事任务) ..> (创建农事任务变更记录2) : include
 (编辑农事任务) <.. (管理农事任务农资2) : extends
 (编辑农事任务) <.. (管理农事任务农机2) : extends
 (编辑农事任务) <.. (管理农事任务地块2) : extends
    (管理农事任务农资2)<..(农事任务农资新增2): extends
    (管理农事任务农资2)<..(农事任务农资修改2): extends
    (管理农事任务农资2)<..(农事任务农资删除2): extends
    (管理农事任务农机2)<..(农事任务农机新增2): extends
    (管理农事任务农机2)<..(农事任务农机修改2): extends
    (管理农事任务农机2)<..(农事任务农机删除2): extends
    (管理农事任务地块2)<..(农事任务地块新增2): extends
    (管理农事任务地块2)<..(农事任务地块修改2): extends
    (管理农事任务地块2)<..(农事任务地块删除2): extends

 任务提出者 --> (撤回农事任务)
   (撤回农事任务) ..> (创建农事任务变更记录3) : include
}

rectangle 确认农事任务完成情况 {
usecase 创建农事任务变更记录 as 创建农事任务变更记录4
  任务提出者 --> (确认完成农事任务)
  (确认完成农事任务) ..> (创建农事任务变更记录4) : include
  (确认完成农事任务) ..> (创建农事记录): include
  (确认完成农事任务) <.. (创建种养计划): extends
  (确认完成农事任务) <.. (创建采收记录): extends
}


rectangle 管理劳作人员 {
  任务提出者 --> (管理劳作人员)
  usecase 新增 as 管理劳作人员新增
  usecase 修改 as 管理劳作人员修改
  usecase 删除 as 管理劳作人员删除
  (管理劳作人员) --> (管理劳作人员新增)
  (管理劳作人员) --> (管理劳作人员修改)
  (管理劳作人员) --> (管理劳作人员删除)
}

@enduml