@startuml
!include ../style.puml
  skinparam arrow {
    Color deeppink
	Thickness 1
	fontsize 10
	fontcolor #blue
  }

left to right direction
actor :农机库管员(co端) :as a

rectangle 管理农机领用子任务 {
usecase 创建农事任务变更记录 as 创建农事任务变更记录9
usecase 创建农机出入库记录 as 创建农机出入记录1
  a --> (领用)
  (领用)  --> (创建农机出入记录1)

  a --> (领用完成)
  (领用完成)<.. (创建农事任务变更记录9) : extends
}

rectangle 管理农机 {
  usecase 新增 as 管理农机新增
  usecase 修改 as 管理农机修改
  usecase 删除 as 管理农机删除
  usecase 创建农机出入库记录 as 创建农机出入记录2


  a --> (管理农机基础数据)

  (管理农机基础数据)--> (管理农机新增)
  (管理农机基础数据)--> (管理农机修改)
  (管理农机基础数据)--> (管理农机删除)



  a --> (出/入库:借出或者领用，归还)
  (出/入库:借出或者领用，归还) --> (创建农机出入记录2)
}

@enduml