@startuml
!include ../style.puml
autonumber  "0."

actor 农资库管员
participant "produce服务" as A



农资库管员->A:发起农资出库请求
activate A
A -> A: 入参校验农资出库子任务id,农资出库入参列表是否有效
activate A
deactivate A
A -> A: 校验农资出库子任务状态是否为**“待出库”**
activate A
deactivate A
A -> A: 校验用户信息是否合法
activate A
deactivate A
A -> A: 校验农资库是否支持扣除\n该农资出库入参列表的种类和数量农资
activate A
deactivate A

A -> A: 查询农事任务农资列表
activate A
deactivate A
A -> A: 查询该农资出库子任务农资出入库记录列表
activate A
deactivate A

A -> A: 校验该次农资出库入参列表种类数量是\n否超出该农资出库子任务尚未出库数据量
activate A
deactivate A

A -> A: 扣除农资库存，并保存农资出入库记录
activate A
deactivate A

A --> 农资库管员: 返回结果
deactivate A

...
...
...
autonumber  "0."

农资库管员->A:发起出库完成请求
activate A
A -> A: 入参校验农事任务id是否有效
activate A
deactivate A
A -> A: 校验农资出库子任务状态是否为**“待出库”**
activate A
deactivate A
A -> A: 校验用户信息是否合法
activate A
deactivate A

A -> A: 查询农事任务农资列表
activate A
deactivate A
A -> A: 查询该农资出库子任务农资出入库记录列表
activate A
deactivate A

A -> A: 校验该农资出库子任务农资是否已全部出库
activate A
deactivate A

A -> A: 修改该农资出库子任务状态是否为**“已出库”**，并更新数据
activate A
deactivate A

A -> A: 校验该农事任务是否有农机领用子任务
activate A
deactivate A

group 没有农机领用子任务或者农机领用子任务状态为**“已处理”**
A -> A: 将农事任务数据状态改为**“待执行”**并更新数据
activate A
A -> A: 组装农事任务变更记录数据并保存数据
activate A
deactivate A
A --> 农资库管员: 返回结果
deactivate A
end

group 有农机领用子任务且农机领用子任务状态为**“待处理”**
A --> 农资库管员: 返回结果
deactivate A
end


@enduml