@startuml
!include ../style.puml
autonumber  "0."

 actor 总监或中队长 as 任务管理者
participant "produce服务" as A


autonumber  "0."
任务管理者->A:删除
activate A
A -> A: 入参校验
A -> A: <1>校验农事任务状态是否为**“关闭”**\n<2>校验用户信息是否合法

A -> A: 操作'农事任务表'删除该农事任务
A -> A:操作'农事任务地块表'删除地块信息
A -> A:当该农事任务下存在农资信息则操作'农事任务农资表'删除农资信息
A -> A:当该农事任务下存在农机信息则操作'农事任务农机表'删除农机信息
A -> A: 组装农事任务变更记录数据,并插入'农事任务变更记录表'

A --> 任务管理者: 返回结果
deactivate A

@enduml