@startuml
!include ../style.puml
autonumber  "0."

actor 农机库管员
participant "produce服务" as A


农机库管员->A:领用
activate A
A -> A: 入参校验
A -> A: <1>校验农机领用子任务状态是否为**“待处理”**\n<2>校验用户信息是否合法


A -> A: <1>查询农事任务农机信息\n<2>查询该农机领用子任务的农机出入库记录列表\n<3> 校验该次农机领用入参中种类是否包含在农事任务农机信息中\n<4> 校验该次农机领用入参中种类数量农机库是否支持领用

A -> A: 领用农机，组装数据、将农机状态改为使用中，并更新'农机表'
A -> A: 组装农机出入记录数据,并插入'农机出入记录表'
A -> A: 计算农事任务农机已出库数量字段,并更新'农事任务农机表'


A --> 农机库管员: 返回结果
deactivate A

@enduml