spring:
  application:
    name:lei-spanner
  profiles:
    active:dev
  thymeleaf:
    cache:true
    check-template:true
    check-template-location:true
    content-type:text/html
    enabled:true
    encoding:UTF-8
    excluded-view-names:''
    mode:HTML5
    prefix:classpath:/templates/
    suffix:.html
  servlet:
    multipart:
      max-request-size:100MB
      max-file-size:200MB
server:
  port:4653
mybatis:
  mapper-locations:classpath:mappers/*xml
  type-aliases-package:com.lei.spanner.mybatis.entity
